apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dev
type: Opaque
data:
  MONGO_ROOT_USERNAME: value
  MONGO_ROOT_PASSWORD: value
  EXPRESS_AUTH_USERNAME: value
  EXPRESS_AUTH_PASSWORD: value
---
apiVersion: v1
kind: Secret
metadata:
  name: notas-app-secret
  namespace: dev
type: Opaque
data:
  SPRING_DATA_MONGODB_URI: value